### PR TITLE
Segments

### LINKED ISSUE #41: Implement the Segments table
**Feature Request:**
Display a Segments table that allows users to view information such as average speed, slope, time, and distance for each segment
This feature is achieved by completing the subtasks below:

- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #47
- [x] #46
- [x] #51

**Expected Outcome:**
Users will be able to view the average speed, slope, time, and distance for each segment. Additionally, clicking on any segment row in the table will highlight the selected segment on the map

**Alternative Solution:**
None

**Verification:**
To verify the features:

- [x]  Rows in the Segments table are clickable.

- [x]  Runs are separated into small segments.

- [x]  The average speed and slope for each segment are accurate.

- [x] Segment information is retrieved correctly from OpenTracks.

- [x] All segments are displayed in the Segments table.

### PR DESCRIPTION
**Pull request by maianh2611**
Implemented features:
- Implemented click functionality for table row @Abdoul111 
- Segmented runs  @Abdoul111 
- Calculated the average speed and slope for each segment @danbin @BDW12
- Stored Segments in a list to facilitate their display in the table OSMDashboard @maianh2611 
- Retrieved information about the start and end of segments from the URI provided by OpenTracks @serbancaia
- Highlighted the corresponding segment when a user clicks on a segment row @B-Mousa 
- Implemented RecyclerView to enhance application performance @Abdoul111

### CODE REVIEW

**Comment by danbin** [comment]
I already reviewed it and everything works fine on my end (Task: Segment  that can calculate the average speed of segments).

**Comment by osamahk1** [comment]
Reviewed and Verified, all is working good for me.

**Comment by B-Mousa** [comment]
I reviewed it on my part, and all looks good.

**Review by serbancaia — APPROVED** [review]
Pull request approved

**Comment by BDW12** [comment]
I reviewed it, everything works on my part.

**Pull request merged**
